mutation Mutation($pairs: [CreateArbitragePairInput!]) {
  createArbitragePairs(pairs: $pairs) {
    id
    createdAt
    updatedAt
    allowTrading
    marketIdentificator2
    marketIdentificator1
    marketType1
    marketType2
  }
}
