query ArbitragePairs($first: Int, $skip: Int, $where: ArbitragePairWhere) {
  arbitragePairs(first: $first, skip: $skip, where: $where) {
    createdAt
    id
    kalshiMarket {
      ticker
      closeTime
      closed
      createdTime
      event_ticker
      marketType
      subtitle
      title
      type
      yesSubtitle
      noSubtitle
      custom
    }
    kalshiMarketTicker
    polymarketMarket {
      id
      icon
      event_id
      endDate
      conditionId
      closed
      active
      image
      negRisk
      negRiskMarketID
      negRiskRequestID
      noAssetId
      question
      slug
      startDate
      type
      yesAssetId
    }
    polymarketMarketID
    revertPolymarket
    updatedAt
    allowTrading
  }
}

